version: "3"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: mariadb_volume
        target: /var/lib/mysql
    networks:
      - autoEver
    tty: true

  spring:
    image: my_spring
    build: ./backend-spring
    container_name: spring
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - autoEver
    tty: true

volumes:
  mariadb_volume:

networks:
  autoEver:
    driver: bridge
