spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/AUTOEVER?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  # 설정들은 spring.io에서 doc에서 찾아서 공부해야한다.
  # jpa설정
  jpa:
    hibernate: # hibernate 사용 설정
      # 애플리케이션 실행 시점에 테이블을 다 지우고, 내가 가진 entity 정보를 보고 다시 테이블 자동 생성
      # if exists drop table 해주고 다시 만들어준다고 보면 된다.
      ddl-auto: create-drop
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: false
        show_sql: false


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#브라우저 요청에 대해 서버 오류시 기본으로 노출할 페이지를 사용할지 여부
server:
  error:
    whitelabel:
      enabled: false
    include-message: always